# Generated by Django 2.2.4 on 2019-10-25 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid value. Use the following symbols: a-z, A-Z, 0-9 or `_`', regex='^[\\w]+$')], verbose_name='Id')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preferences',
            },
        ),
    ]
