# Generated by Django 2.2.4 on 2019-10-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('quantity_type', models.CharField(choices=[('bushels', 'Bushels'), ('kilograms', 'Kilograms')], default='bushels', max_length=255, verbose_name='Quantity type')),
                ('preferences', models.ManyToManyField(blank=True, related_name='ingredients', to='macroplate.Preference')),
                ('is_protein', models.BooleanField(default=False, verbose_name='Is Protein?'),),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
