# Generated by Django 2.2.4 on 2019-10-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Quantity Type')),
            ],
            options={
                'verbose_name': 'Quantity Type',
                'verbose_name_plural': 'Quantity Types',
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macroplate.QuantityType', verbose_name='Quantity Type'),
        ),
    ]
