# Generated by Django 2.2.4 on 2019-10-28 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid value. Use the following symbols: a-z, A-Z, 0-9 or `_`', regex='^[\\w]+$')], verbose_name='Id')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
            ],
            options={
                'verbose_name': 'Plan Type',
                'verbose_name_plural': 'Plan Types',
            },
        ),
        migrations.CreateModel(
            name='SubMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_instructions', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('best_buy', models.DateField(blank=True, verbose_name='Best buy')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_meals', to='macroplate.PlanType')),
            ],
            options={
                'verbose_name': 'Sub Meal',
                'verbose_name_plural': 'Sub Meals',
            },
        ),
        migrations.CreateModel(
            name='SubMealIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=19, max_length=500, verbose_name='Quantity')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroplate.Ingredient', verbose_name='Plan Type')),
                ('sub_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='macroplate.SubMeal')),
            ],
            options={
                'verbose_name': 'Sub Meal Ingredient',
                'verbose_name_plural': 'Sub Meal Ingredients',
            },
        ),
    ]
