# Generated by Django 2.2.4 on 2019-10-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0003_auto_20191025_1042'),
        ('macroplate', '0004_auto_20191028_0427'),
    ]

    operations = [
    ]
