# Generated by Django 2.2.4 on 2019-10-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0005_merge_20191028_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Meal Name')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Breakfast?')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='MealPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_meals', to='macroplate.Meal')),
                ('sub_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='macroplate.SubMeal', verbose_name='Sub Meal')),
            ],
        ),
    ]
