# Generated by Django 2.2.4 on 2019-10-30 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0006_meal_mealpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, max_length=255, verbose_name='Address')),
                ('suite', models.CharField(blank=True, max_length=255, verbose_name='Suite')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('zip', models.CharField(blank=True, max_length=255, verbose_name='Zip')),
                ('first_delivery_date', models.DateField(blank=True, null=True, verbose_name='First Delivery')),
                ('delivery_notes', models.TextField(blank=True, max_length=350, verbose_name='Delivery Notes')),
                ('delivery_window', models.TextField(blank=True, max_length=500, verbose_name='Delivery Window')),
                ('red', models.BooleanField(default=False, verbose_name='RED')),
                ('plan_frequency', models.PositiveSmallIntegerField(choices=[(2, 'On the Go (2 meals)'), (3, 'Standard (3 meals)'), (4, 'Performance (4 meals)'), (5, 'Athlete (5 meals)')], default=2, verbose_name='Plan Frequency')),
                ('five_or_seven_days', models.PositiveSmallIntegerField(choices=[(5, '5 Days'), (7, '7 Days')], default=5)),
                ('breakfast', models.BooleanField(default=False, verbose_name='Breakfast?')),
                ('protein_snacks', models.PositiveSmallIntegerField(choices=[(1, '1/day'), (2, '2/day'), (3, '3/day')], default=1, verbose_name='Protein snacks')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notes')),
                ('gluten_free', models.BooleanField(default=False, verbose_name='Gluten Free?')),
                ('nut_free', models.BooleanField(default=False, verbose_name='Nut Free?')),
                ('cold_pressed_juice', models.PositiveSmallIntegerField(choices=[(4, '4/week'), (5, '5/week'), (6, '6/week'), (7, '7/week'), (8, '8/week'), (9, '9/week')], default=4, verbose_name='Cold Pressed Juice?')),
                ('juice_requested', models.TextField(blank=True, max_length=500, verbose_name='Juice Requested')),
                ('juice_dislikes', models.TextField(blank=True, max_length=500, verbose_name='Juice Dislikes')),
                ('cold_brew', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Cold Brew?')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macroplate.PlanType', verbose_name='Plan Type')),
                ('preferences', models.ManyToManyField(blank=True, related_name='customers', to='macroplate.Preference')),
            ],
        ),
    ]
