# Generated by Django 2.2.4 on 2019-11-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meal_assignment_paused',
            field=models.BooleanField(default=False, verbose_name='Pause meal assignment?'),
        ),
    ]
