# Generated by Django 2.2.4 on 2019-11-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0008_customer_meal_assignment_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('monday', models.PositiveIntegerField(verbose_name='Monday')),
                ('tuesday', models.PositiveIntegerField(verbose_name='Tuesday')),
                ('wednesday', models.PositiveIntegerField(verbose_name='Wednesday')),
                ('thursday', models.PositiveIntegerField(verbose_name='Thursday')),
                ('friday', models.PositiveIntegerField(verbose_name='Friday')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='macroplate.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Weekly schedule',
                'verbose_name_plural': 'Weekly schedules',
                'unique_together': {('customer', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Day of week')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('breakfasts', models.PositiveIntegerField(verbose_name='Breakfasts')),
                ('lunches', models.PositiveIntegerField(verbose_name='Lunches')),
                ('dinners', models.PositiveIntegerField(verbose_name='Dinners')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='macroplate.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Daily schedule',
                'verbose_name_plural': 'Daily schedules',
                'unique_together': {('customer', 'day_of_week', 'date')},
            },
        ),
    ]
