# Generated by Django 2.2.4 on 2019-11-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0009_dailyschedule_weeklyschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='plan_frequency',
            new_name='dishes_per_day',
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='day_of_week',
            field=models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of week'),
        ),
    ]
