# Generated by Django 2.2.4 on 2019-11-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0010_auto_20191113_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='macroplate.Customer', verbose_name='Customer'),
        ),
    ]
