# Generated by Django 2.2.4 on 2019-11-14 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0011_auto_20191113_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='First Delivery'),
            preserve_default=False,
        ),
    ]
