# Generated by Django 2.2.4 on 2019-11-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0011_auto_20191113_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantype',
            name='default',
        ),
        migrations.AddField(
            model_name='plantype',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Unique'),
        ),
    ]
