# Generated by Django 2.2.4 on 2019-11-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0012_auto_20191114_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True, verbose_name='Date')),
                ('meals', models.ManyToManyField(related_name='menus_not_unique', to='macroplate.Meal', verbose_name='Meals')),
                ('unique_meals', models.ManyToManyField(related_name='menus_unique', to='macroplate.Meal', verbose_name='Unique Meals')),
            ],
            options={
                'verbose_name': 'Daily Menu',
                'verbose_name_plural': 'Daily Menus',
            },
        ),
    ]
