# Generated by Django 2.2.4 on 2019-11-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0013_dailymenu'),
        ('macroplate', '0012_auto_20191114_0131'),
    ]

    operations = [
    ]
