# Generated by Django 2.2.4 on 2019-11-15 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0014_merge_20191115_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
