# Generated by Django 2.2.4 on 2019-11-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0016_assignedmeal_assignedmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedmeal',
            name='assigned_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_meals', to='macroplate.AssignedMenu', verbose_name='Assigned menu'),
        ),
        migrations.CreateModel(
            name='SubMealModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_type', models.PositiveSmallIntegerField(choices=[(0, 'NO'), (1, 'SUB'), (2, 'EXTRA')], default=0, verbose_name='Modifier type')),
                ('ingredient_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods_from', to='macroplate.Ingredient', verbose_name='Ingredient from')),
                ('ingredient_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods_to', to='macroplate.Ingredient', verbose_name='Ingredient to')),
                ('sub_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='macroplate.SubMeal', verbose_name='Sub meal')),
            ],
            options={
                'verbose_name': 'Sub Meal Modifier',
                'verbose_name_plural': 'Sub Meal Modifiers',
                'unique_together': {('sub_meal', 'ingredient_from')},
            },
        ),
    ]
