# Generated by Django 2.2.4 on 2019-11-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0017_auto_20191119_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='submeal',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_meals', to='macroplate.Meal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='submealingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=19, max_length=500, verbose_name='Quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='submeal',
            unique_together={('meal', 'plan_type')},
        ),
        migrations.DeleteModel(
            name='MealPart',
        ),
    ]
