# Generated by Django 2.2.4 on 2019-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0019_auto_20191121_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantype',
            name='unique',
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='meals',
            field=models.ManyToManyField(related_name='daily_menus', to='macroplate.Meal', verbose_name='Meals'),
        ),
    ]
