# Generated by Django 2.2.4 on 2019-11-21 06:35
from django.db import migrations, models

from apps.core.utils import clear_string


def add_unique_names(apps, schema_editor):
    """Add unique names for all plans.

    In case of collision, add postfix (issue XXX) to name
    """
    PlanType = apps.get_model('macroplate', 'PlanType')
    Ingredient = apps.get_model('macroplate', 'Ingredient')
    Preference = apps.get_model('macroplate', 'Preference')
    QuantityType = apps.get_model('macroplate', 'QuantityType')

    for model in [PlanType, Ingredient, Preference, QuantityType]:
        issues = 1
        for obj in model.objects.all():
            try:
                obj.name_unique = clear_string(obj.name)
                obj.save()
            except Exception:
                obj.name = obj.name + f' (issue {issues})'
                obj.name_unique = clear_string(obj.name)
                obj.save()
                issues += 1


class Migration(migrations.Migration):
    dependencies = [
        ('macroplate', '0020_auto_20191121_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name_unique',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantype',
            name='name_unique',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='name_unique',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantitytype',
            name='name_unique',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.RunPython(
            add_unique_names,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
