# Generated by Django 2.2.4 on 2019-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0021_auto_20191121_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name_unique',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='name_unique',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='name_unique',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quantitytype',
            name='name_unique',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
