# Generated by Django 2.2.4 on 2019-11-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0022_auto_20191121_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='count',
            field=models.BooleanField(default=False, verbose_name='Count?'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(choices=[('ct', 'Count'), ('oz', 'Ounce(s)'), ('g', 'Gram(s)'), ('kg', 'Kilogram(s)'), ('lb', 'Pound(s) (lbs)'), ('us_g', 'Gallon(s)'), ('us_qt', 'Quart(s)'), ('us_pint', 'Pint(s)'), ('us_cup', 'Cup(s)'), ('us_oz', 'Fluid Ounce(s)'), ('us_tbsp', 'Tablespoon(s) '), ('us_tsp', 'Teaspoon(s)'), ('ml', 'Milliliter(s)'), ('l', 'Liter(s)'), ('bsh', 'Bushel(s)')], default='oz', max_length=25, verbose_name='Quantity Type'),
        ),
        migrations.DeleteModel(
            name='QuantityType',
        ),
    ]
