# Generated by Django 2.2.4 on 2019-11-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0023_auto_20191122_0324'),
        ('macroplate', '0024_auto_20191125_0108'),
    ]

    operations = [
    ]
