# Generated by Django 2.2.4 on 2019-11-25 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0024_auto_20191125_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealmodifier',
            name='ingredient_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mods_to', to='macroplate.Ingredient', verbose_name='Ingredient to'),
        ),
    ]
