# Generated by Django 2.2.4 on 2019-11-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0025_merge_20191125_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.CharField(default=1, editable=False, max_length=50, verbose_name='External ID'),
            preserve_default=False,
        ),
    ]
