# Generated by Django 2.2.4 on 2019-11-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0025_merge_20191125_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Promo code'),
        ),
    ]
