# Generated by Django 2.2.4 on 2019-11-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0025_merge_20191125_0543'),
        ('macroplate', '0025_auto_20191125_0149'),
    ]

    operations = [
    ]
