# Generated by Django 2.2.4 on 2019-11-25 12:32

from django.db import migrations


def add_external_id(apps, schema_editor):
    """Add unique external id to each customer."""
    Customer = apps.get_model('macroplate', 'Customer')

    for obj in Customer.objects.all():
        obj.external_id = obj.id
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('macroplate', '0026_customer_external_id'),
    ]

    operations = [
        migrations.RunPython(
            add_external_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
