# Generated by Django 2.2.4 on 2019-11-25 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0027_add_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid value. Use the following symbols: a-z, A-Z, 0-9, `-` or `_`', regex='^[\\w-]+$')], verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid value. Use the following symbols: a-z, A-Z, 0-9, `-` or `_`', regex='^[\\w-]+$')], verbose_name='Id'),
        ),
    ]
