# Generated by Django 2.2.4 on 2019-11-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0026_merge_20191126_0829'),
        ('macroplate', '0028_auto_20191125_1235'),
        ('macroplate', '0026_customer_promo_code'),
    ]

    operations = [
    ]
