# Generated by Django 2.2.4 on 2019-11-26 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0030_auto_20191126_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coffee_count',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Coffee Count'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='juice_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No juice'), (4, '4/week'), (5, '5/week'), (6, '6/week'), (7, '7/week'), (8, '8/week'), (9, '9/week')], default=0, verbose_name='Juice Count'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='snacks_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No snacks'), (1, '1/day'), (2, '2/day'), (3, '3/day')], default=0, verbose_name='Snacks Count'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='snacks_notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Snacks Notes'),
        ),
    ]
