# Generated by Django 2.2.4 on 2019-11-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0031_auto_20191126_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedmeal',
            name='assigned_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=15, null=True),
        ),
    ]
