# Generated by Django 2.2.4 on 2019-11-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0032_assignedmeal_assigned_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedmeal',
            old_name='assigned_type',
            new_name='meal_type',
        ),
    ]
