# Generated by Django 2.2.4 on 2019-11-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0033_auto_20191127_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedmenu',
            name='is_approved',
        ),
    ]
