# Generated by Django 2.2.4 on 2019-11-28 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0034_remove_assignedmenu_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='conversion_raw',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=19, max_length=500, verbose_name='Conversion Raw'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='macroplate.PlanType', verbose_name='Plan Type'),
        ),
    ]
