# Generated by Django 2.2.4 on 2019-12-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0036_auto_20191204_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferences_notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Preferences Notes'),
        ),
    ]
