# Generated by Django 2.2.4 on 2019-12-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0037_customer_preferences_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealmodifier',
            name='is_soft',
            field=models.BooleanField(default=False, verbose_name='Is soft'),
        ),
    ]
