# Generated by Django 2.2.4 on 2019-12-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0038_mealmodifier_is_soft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='meals',
        ),
        migrations.AlterField(
            model_name='mealmodifier',
            name='is_soft',
            field=models.BooleanField(default=False, verbose_name='Flex'),
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroplate.DailyMenu')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroplate.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='items',
            field=models.ManyToManyField(related_name='daily_menus', through='macroplate.DailyMenuItem', to='macroplate.Meal', verbose_name='Meals'),
        ),
    ]
