# Generated by Django 2.2.4 on 2019-12-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0039_auto_20191226_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymenu',
            old_name='items',
            new_name='meals',
        ),
    ]
