# Generated by Django 2.2.4 on 2020-01-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0040_auto_20191226_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='excluded_meals',
            field=models.ManyToManyField(blank=True, related_name='excluded_meals', to='macroplate.Meal', verbose_name='Meals Exclusion'),
        ),
    ]
