# Generated by Django 2.2.4 on 2020-01-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0041_customer_excluded_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferences',
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_api', models.BooleanField(default=False, verbose_name='From API')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroplate.Customer')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macroplate.Preference')),
            ],
        ),
    ]
