# Generated by Django 2.2.4 on 2020-01-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0042_auto_20200120_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='customers', through='macroplate.CustomerPreference', to='macroplate.Preference'),
        ),
    ]
