# Generated by Django 2.2.4 on 2020-01-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0043_customer_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_meals',
            field=models.ManyToManyField(blank=True, related_name='preferred_meals', to='macroplate.Meal', verbose_name='Preferred Meals'),
        ),
    ]
