# Generated by Django 2.2.4 on 2020-01-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0044_customer_preferred_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='manually_confirmed',
            field=models.BooleanField(default=False, verbose_name='Manually Confirmed'),
        ),
    ]
