# Generated by Django 2.2.4 on 2020-04-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0047_customernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='is_modified',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='is_modified',
        ),
    ]
