# Generated by Django 2.2.4 on 2020-04-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0048_auto_20200420_0806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='start_date',
        ),
    ]
