# Generated by Django 2.2.13 on 2020-07-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0051_auto_20200703_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='First Delivery'),
        ),
        migrations.AddField(
            model_name='customer',
            name='latest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='macroplate.Customer'),
        ),
    ]
