# Generated by Django 2.2.4 on 2020-10-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0053_auto_20201013_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Delivery'),
        ),
    ]
