# Generated by Django 2.2.4 on 2021-05-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0055_auto_20210303_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated at'),
        ),
    ]
