# Generated by Django 2.2.4 on 2022-05-19 09:23

from django.db import migrations, models


class AssignedMealType:
    """Types for assigned meals."""
    LUNCH = 'lunch'
    DINNER = 'dinner'


def move_dinners_to_lunches(apps, schema_editor):
    """Move `dinners` count to `lunches` for DailySchedule.

    Update AssignedMeal objects with "dinner" meal_type
    to have "lunch" meal_type instead.
    """
    DailySchedule = apps.get_model('macroplate', 'DailySchedule')
    AssignedMeal = apps.get_model('macroplate', 'AssignedMeal')

    DailySchedule.objects.update(
        lunches=models.F('lunches') + models.F('dinners'),
    )
    AssignedMeal.objects.filter(
        meal_type=AssignedMealType.DINNER,
    ).update(
        meal_type=AssignedMealType.LUNCH,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0057_auto_20220112_0336'),
    ]

    operations = [
        migrations.RunPython(
            code=move_dinners_to_lunches,
            reverse_code=migrations.RunPython.noop,
            elidable=True
        ),
        migrations.RemoveField(
            model_name='dailyschedule',
            name='dinners',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dishes_per_day',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='five_or_seven_days',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='has_delivery',
            field=models.BooleanField(default=True, help_text='Is delivery made on this date or not.', verbose_name='Has delivery?'),
        ),
        migrations.AlterField(
            model_name='assignedmeal',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch')], max_length=15, null=True),
        ),
    ]
