# Generated by Django 2.2.4 on 2022-06-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macroplate', '0058_auto_20220519_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='breakfast',
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
