# Generated by Django 2.2.4 on 2019-10-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191022_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='location_updated',
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('customer_service', 'Customer Service'), ('kitchen_staff', 'Kitchen Staff')], default='customer_service', help_text='The user role.', max_length=20, verbose_name='Role'),
        ),
    ]
